apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - port: 80
      targetPort: 8080   
      nodePort: 30000   
  type: {{ .Values.api.serviceType }}